---
- name: 'Create Folder {{ wp_name }}'
  file:
    path: '{{ item }}'
    state: directory
  loop:
    - '{{ wp_path }}/config'

- name: 'Deploy {{ wp_name }}'
  community.docker.docker_container:
    name: '{{ wp_name }}'
    image: wordpress:latest
    networks:
      - name: '{{ network_name }}'
    env:
      WORDPRESS_DB_HOST: '{{ sql_name }}'
      WORDPRESS_DB_NAME: '{{ db_name }}'
      WORDPRESS_DB_USER: '{{ db_user }}'
      WORDPRESS_DB_PASSWORD: '{{ db_pass }}'
    volumes:
      - '{{ wp_path }}/:/var/www/html/'
    restart_policy: always