---
- name: Enabled UFW
  ufw:
    state: enabled
    # policy: allow

- name: Deny Incoming
  ufw:
    direction: incoming
    policy: deny

- name: Allow Outgoing
  ufw:
    direction: outgoing
    policy: allow

- name: Allow Ports
  ufw:
    rule: allow
    port: '{{ item }}'
    proto: tcp
  loop:
    - '22'
    - '80'
    - '443'