---
- name: Create Folder MySQL
  file:
    path: '{{ item }}'
    state: directory
  loop:
    - '{{ sql_path }}/config'
    - '{{ sql_path }}/data'

- name: Deploy MYSQL
  community.docker.docker_container:
    name: '{{ sql_name }}'
    image: mysql:latest
    networks:
      - name: '{{ network_name }}'
    volumes:
      - '{{ sql_path }}/config/my.conf:/etc/mysql/conf.d/config-file.cnf'
      - '{{ sql_path }}/data:/var/lib/mysql:rw'
    env:
      MYSQL_DATABASE: '{{ db_name }}'
      MYSQL_USER: '{{ db_user }}'
      MYSQL_PASSWORD: '{{ db_pass }}'
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    restart_policy: always