---
- name: 'Deploy {{ pma_name }}'
  community.docker.docker_container:
    name: '{{ pma_name }}'
    image: phpmyadmin
    ports:
      - 8081:80
    networks:
      - name: '{{ network_name }}'
    env:
      PMA_HOST: '{{ sql_name }}'
      PMA_ABSOLUTE_URI: 'https://{{ domain }}{{ pma_uri }}/'
    restart_policy: always